// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e3f2f517-6b1e-47bd-9eae-008c28ea43a7",
    "aws_cognito_region": "eu-west-1",
    "aws_mobile_analytics_app_id": "f90655b277ce497dabb678acda9093b5",
    "aws_mobile_analytics_app_region": "eu-west-1",
    "aws_content_delivery_bucket": "mymplifyroject-20190209175156-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://mymplifyroject-20190209175156-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
